[package]
name = "struct_traits"
version = "0.1.0"
authors = ["lets code <letscode786@gmai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
